import React, { useState, useRef, useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

type Role = 'admin' | 'user';

type LoginParam = {
  username: string;
  password: string;
};

type User = LoginParam & {
  role: Role;
};

export default function Home() {
  const usernameRef = useRef<HTMLInputElement>(null);
  const passwordRef = useRef<HTMLInputElement>(null);

  const handleLogin = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    console.log(
      JSON.stringify({
        username: usernameRef.current?.value,
        password: passwordRef.current?.value,
      })
    );
    fetch('/api/login', {
      body: JSON.stringify({
        username: usernameRef.current?.value,
        password: passwordRef.current?.value,
      }),
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
    })
      .then((res) => {
        switch (res.status) {
          case 200:
            res.json().then((data) => console.log(data));
            break;
          case 401:
            res.json().then((data) => console.log(data.error));
            break;
          default:
            console.log('Unknown error');
        }
      })
      .catch((error) => console.log(error))
      .finally(() => {
        usernameRef.current!.value = '';
        passwordRef.current!.value = '';
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <label htmlFor="username">Username</label>
        <input ref={usernameRef} id="username" type="text"></input>
        <label htmlFor="username">Password</label>
        <input ref={passwordRef} id="password" type="password"></input>
        <button onClick={handleLogin}>LOGIN</button>
      </main>
    </div>
  );
}
